import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased selection:bg-primary selection:text-primary-foreground`}
      >
        <div className="flex min-h-svh flex-col">
          <SiteHeader />
          <main className="flex-1" id="content">
            {children}
          </main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
